name: Build and Test

on:
  pull_request:
    branches:
      - main 
jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: check format
        run: |
          cd Compiler
          chmod +x build.sh 
          ./build.sh check_format # Check that the code follows llvm style

      - name: Run all required checks for a PR to main
        run: |
          cd Compiler
          chmod +x build.sh 
          ./build.sh setup # build the code and has clang-tidy automatically run when building
          ./build.sh test # run all catch2 unit test and fail if coverage is less that 100%

