name: Build and Test

on:
  pull_request:
    branches:
      - main 
jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install CMake and Ninja
        run: |
          cd Compiler
          chmod +x build.sh 
          ./build.sh setup
          ./build.sh test
